// <auto-generated />
using System;
using BackendProject.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendProject.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BackendProject.App.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("BackendProject.App.Models.PublicacaoReceita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Deliciosos")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NotaMedia")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeVotos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DataPublicacao");

                    b.HasIndex("ReceitaId")
                        .IsUnique();

                    b.ToTable("PublicacoesReceitas");
                });

            modelBuilder.Entity("BackendProject.App.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModoPreparo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("BackendProject.App.Models.ReceitaAmada", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataMarcacao")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId", "ReceitaId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitasAmadas");
                });

            modelBuilder.Entity("BackendProject.App.Models.ReceitaDeliciosa", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataMarcacao")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId", "ReceitaId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitasDeliciosas");
                });

            modelBuilder.Entity("BackendProject.App.Models.ReceitaIngrediente", b =>
                {
                    b.Property<int>("ReceitaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quantidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReceitaId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("ReceitaIngredientes");
                });

            modelBuilder.Entity("BackendProject.App.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instagram")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TikTok")
                        .HasColumnType("TEXT");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Apelido")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BackendProject.App.Models.PublicacaoReceita", b =>
                {
                    b.HasOne("BackendProject.App.Models.Receita", "Receita")
                        .WithOne("Publicacao")
                        .HasForeignKey("BackendProject.App.Models.PublicacaoReceita", "ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("BackendProject.App.Models.Receita", b =>
                {
                    b.HasOne("BackendProject.App.Models.Usuario", "Usuario")
                        .WithMany("Receitas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendProject.App.Models.ReceitaAmada", b =>
                {
                    b.HasOne("BackendProject.App.Models.Receita", "Receita")
                        .WithMany("UsuariosQueAmaram")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendProject.App.Models.Usuario", "Usuario")
                        .WithMany("ReceitasAmadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendProject.App.Models.ReceitaDeliciosa", b =>
                {
                    b.HasOne("BackendProject.App.Models.Receita", "Receita")
                        .WithMany("UsuariosQueAprovaram")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendProject.App.Models.Usuario", "Usuario")
                        .WithMany("ReceitasDeliciosas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendProject.App.Models.ReceitaIngrediente", b =>
                {
                    b.HasOne("BackendProject.App.Models.Ingrediente", "Ingrediente")
                        .WithMany("ReceitaIngredientes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendProject.App.Models.Receita", "Receita")
                        .WithMany("ReceitaIngredientes")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("BackendProject.App.Models.Ingrediente", b =>
                {
                    b.Navigation("ReceitaIngredientes");
                });

            modelBuilder.Entity("BackendProject.App.Models.Receita", b =>
                {
                    b.Navigation("Publicacao");

                    b.Navigation("ReceitaIngredientes");

                    b.Navigation("UsuariosQueAmaram");

                    b.Navigation("UsuariosQueAprovaram");
                });

            modelBuilder.Entity("BackendProject.App.Models.Usuario", b =>
                {
                    b.Navigation("Receitas");

                    b.Navigation("ReceitasAmadas");

                    b.Navigation("ReceitasDeliciosas");
                });
#pragma warning restore 612, 618
        }
    }
}
